language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp34-*"

matrix:
  include:
    - python: 3.5
      cache: pip
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
      env: WHEEL=0

    - sudo: required
      services:
        - docker
      env:
        - WHEEL=1
        - PIP=pip
        - CIBW_BEFORE_BUILD="if [ ! -f built-lib ]; then wget https://s3.amazonaws.com/xanadu-img/lapack-3.4.2.tgz && tar xzf lapack-3.4.2.tgz && cd lapack-3.4.2 && make install PREFIX=/usr/local && cd ../; fi"

before_install:
  - |
    if [ "$WHEEL" = "0" ]; then
      sudo apt-get -qq update;
      sudo apt-get install -y liblapacke-dev;
    fi

install:
  - |
    if [ "$WHEEL" = "0" ]; then
      pip install -r requirements.txt
      pip install wheel coverage codecov
      pip install -e .
    fi

script:
  - if [ "$WHEEL" = "0" ]; then make coverage; fi
  - |
    if [ "$WHEEL" = "1" ]; then
      $PIP install cibuildwheel==0.8.0
      cibuildwheel --output-dir wheelhouse
    fi

after_success:
  - if [ "$WHEEL" = "0" ]; then make codecov; fi
