before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblapacke-dev libgomp1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
language: python
cache: pip
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install wheel coverage codecov
  - pip install -e .
script:
  - make coverage
after_success:
  - codecov
