dist: bionic
language: python
matrix:
  include:
  - python: 3.6
    cache: pip
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc
before_install:
- |
  sudo apt-get -qq update;
  sudo apt-get install -y libeigen3-dev libblas-dev liblapack-dev;
install:
- |
    pip install -r requirements.txt
    pip install pytest pytest-cov wheel codecov
    pip install -e .
script:
- make coverage
after_success:
- codecov
