language: python

env:
  global:
    - CIBW_SKIP=cp27-*

matrix:
  include:
    - python: 3.5
      cache: pip
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
      env: WHEEL=0

    - sudo: required
      services:
        - docker
      env:
        - WHEEL=1
        - PIP=pip
        - CIBW_BEFORE_BUILD=wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo && yum install -y devtoolset-2-gcc devtoolset-2-gcc-c++ devtoolset-2-binutils lapack-devel && source /opt/rh/devtoolset-2/enable

    - os: osx
      osx_image: xcode6.4 # = OS X 10.10
      language: generic
      env:
        - WHEEL=1
        - PIP=pip3

before_install:
  - |
    if [ "$WHEEL" = "0" ]; then
      sudo apt-get -qq update;
      sudo apt-get install -y liblapacke-dev;
    fi

install:
  - |
    if [ "$WHEEL" = "0" ]; then
      pip install -r requirements.txt
      pip install wheel coverage codecov
      pip install -e .
    fi

script:
  - if [ "$WHEEL" = "0" ]; then make coverage; fi
  - |
    if [ "$WHEEL" = "1" ]; then
      $PIP install cibuildwheel==0.8.0
      cibuildwheel --output-dir wheelhouse
    fi

after_success:
  - if [ "$WHEEL" = "0" ]; then make codecov; fi
